version: '3.8'

services:
  user-microservice:
    build:
      context: ./Booking-Application/User-Microservice
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=userdb;port=3306;database=userdb;user=myuser;password=mypassword
    depends_on:
      - userdb
    restart: unless-stopped

  booking-microservice:
    build:
      context: ./Booking-Application/Booking-Microservice
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=bookingdb;port=3306;database=bookingdb;user=myuser;password=mypassword
    depends_on:
      - bookingdb
    restart: unless-stopped

  userdb:
    image: mariadb:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"

  bookingdb:
    image: mariadb:latest
    container_name: bookingdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookingdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Booking-Application/API-Gateway/Dockerfile
    ports:
      - "8080:80"
    environment:
      AuthenticationProviderKey: "mMdAhocQbIAa1/4iD8W5BiDCD9Lxg9ULp4qROgJVN8oRZommyAsnRalnNlzWGbKGJItr/kh2jVd2d9brhSBAJttV7NE47dvyX6n36cFKlnz3k9AodqqVgH/S52oQMYamtI+HsQqBmsvZMqOE+oGlEIzJG9tmDZ1JE/qJHq+bXo3RCEuBf26dGuIG4DWpjh+G4xTVC7ZoByCmq5zTUUyTlFZCQ2483iJe1Thkem9mlzt3cOy8O5SYJBafIb0xdIBYEoHl56Z805fO/W4eAw+M5stSCUdJTBUtWbCiId9zSapmilb20sCg4l5xYTsaJImTfHlo0t9kF1o/RXwr1cw3zCPoyt9tjWhZ83LMsi1ydBg="
    networks:
      - booking_network

volumes:
  mongodb_data:

networks:
  booking_network:
    driver: bridge
